package com.boot.star.model;

import java.math.BigDecimal;
import java.util.Date;

public class OpensaleHouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.HouseId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer houseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.HouseName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String housename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.Status
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.CanSelling
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Boolean canselling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.BuildingId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer buildingid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.BuildingNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String buildingno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.PartNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String partno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.FloorNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String floorno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.RoomNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.HouseType
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String housetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.BuildingArea
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal buildingarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.UsingArea
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal usingarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.UnitPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal unitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.TotalPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal totalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.Memo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.ChipsNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String chipsno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.CustomerId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.SaleDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Date saledate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.IsBookPrint
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Boolean isbookprint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.BookPrintDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Date bookprintdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.IsBookSign
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Boolean isbooksign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.BookSignDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Date booksigndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.PaySolution
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer paysolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.FloorSortNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer floorsortno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.LockedBy
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer lockedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.LockedDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Date lockeddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.SubscribingGuid
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String subscribingguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.BookPrintTimes
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer bookprinttimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.ProductType
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String producttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.ProtocolAmount
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal protocolamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.PaymentMethodName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String paymentmethodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.PayedTime
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Date payedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.CustomerNames
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String customernames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.Nullify
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Boolean nullify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.SaleID
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer saleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.SaleName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private String salename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.FloorBuiltPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal floorbuiltprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.FloorSetInPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal floorsetinprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.FloorTotalPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal floortotalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.DecoratePrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private BigDecimal decorateprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OpenSale_House.ProductTypeId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    private Integer producttypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.HouseId
     *
     * @return the value of OpenSale_House.HouseId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getHouseid() {
        return houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.HouseId
     *
     * @param houseid the value for OpenSale_House.HouseId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setHouseid(Integer houseid) {
        this.houseid = houseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.HouseName
     *
     * @return the value of OpenSale_House.HouseName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getHousename() {
        return housename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.HouseName
     *
     * @param housename the value for OpenSale_House.HouseName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setHousename(String housename) {
        this.housename = housename == null ? null : housename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.Status
     *
     * @return the value of OpenSale_House.Status
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.Status
     *
     * @param status the value for OpenSale_House.Status
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.CanSelling
     *
     * @return the value of OpenSale_House.CanSelling
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Boolean getCanselling() {
        return canselling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.CanSelling
     *
     * @param canselling the value for OpenSale_House.CanSelling
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setCanselling(Boolean canselling) {
        this.canselling = canselling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.BuildingId
     *
     * @return the value of OpenSale_House.BuildingId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getBuildingid() {
        return buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.BuildingId
     *
     * @param buildingid the value for OpenSale_House.BuildingId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setBuildingid(Integer buildingid) {
        this.buildingid = buildingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.BuildingNo
     *
     * @return the value of OpenSale_House.BuildingNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getBuildingno() {
        return buildingno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.BuildingNo
     *
     * @param buildingno the value for OpenSale_House.BuildingNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setBuildingno(String buildingno) {
        this.buildingno = buildingno == null ? null : buildingno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.PartNo
     *
     * @return the value of OpenSale_House.PartNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getPartno() {
        return partno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.PartNo
     *
     * @param partno the value for OpenSale_House.PartNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setPartno(String partno) {
        this.partno = partno == null ? null : partno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.FloorNo
     *
     * @return the value of OpenSale_House.FloorNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getFloorno() {
        return floorno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.FloorNo
     *
     * @param floorno the value for OpenSale_House.FloorNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setFloorno(String floorno) {
        this.floorno = floorno == null ? null : floorno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.RoomNo
     *
     * @return the value of OpenSale_House.RoomNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.RoomNo
     *
     * @param roomno the value for OpenSale_House.RoomNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno == null ? null : roomno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.HouseType
     *
     * @return the value of OpenSale_House.HouseType
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.HouseType
     *
     * @param housetype the value for OpenSale_House.HouseType
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setHousetype(String housetype) {
        this.housetype = housetype == null ? null : housetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.BuildingArea
     *
     * @return the value of OpenSale_House.BuildingArea
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getBuildingarea() {
        return buildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.BuildingArea
     *
     * @param buildingarea the value for OpenSale_House.BuildingArea
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setBuildingarea(BigDecimal buildingarea) {
        this.buildingarea = buildingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.UsingArea
     *
     * @return the value of OpenSale_House.UsingArea
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getUsingarea() {
        return usingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.UsingArea
     *
     * @param usingarea the value for OpenSale_House.UsingArea
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setUsingarea(BigDecimal usingarea) {
        this.usingarea = usingarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.UnitPrice
     *
     * @return the value of OpenSale_House.UnitPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.UnitPrice
     *
     * @param unitprice the value for OpenSale_House.UnitPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.TotalPrice
     *
     * @return the value of OpenSale_House.TotalPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.TotalPrice
     *
     * @param totalprice the value for OpenSale_House.TotalPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.Memo
     *
     * @return the value of OpenSale_House.Memo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.Memo
     *
     * @param memo the value for OpenSale_House.Memo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.ChipsNo
     *
     * @return the value of OpenSale_House.ChipsNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getChipsno() {
        return chipsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.ChipsNo
     *
     * @param chipsno the value for OpenSale_House.ChipsNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setChipsno(String chipsno) {
        this.chipsno = chipsno == null ? null : chipsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.CustomerId
     *
     * @return the value of OpenSale_House.CustomerId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.CustomerId
     *
     * @param customerid the value for OpenSale_House.CustomerId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.SaleDate
     *
     * @return the value of OpenSale_House.SaleDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Date getSaledate() {
        return saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.SaleDate
     *
     * @param saledate the value for OpenSale_House.SaleDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setSaledate(Date saledate) {
        this.saledate = saledate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.IsBookPrint
     *
     * @return the value of OpenSale_House.IsBookPrint
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Boolean getIsbookprint() {
        return isbookprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.IsBookPrint
     *
     * @param isbookprint the value for OpenSale_House.IsBookPrint
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setIsbookprint(Boolean isbookprint) {
        this.isbookprint = isbookprint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.BookPrintDate
     *
     * @return the value of OpenSale_House.BookPrintDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Date getBookprintdate() {
        return bookprintdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.BookPrintDate
     *
     * @param bookprintdate the value for OpenSale_House.BookPrintDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setBookprintdate(Date bookprintdate) {
        this.bookprintdate = bookprintdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.IsBookSign
     *
     * @return the value of OpenSale_House.IsBookSign
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Boolean getIsbooksign() {
        return isbooksign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.IsBookSign
     *
     * @param isbooksign the value for OpenSale_House.IsBookSign
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setIsbooksign(Boolean isbooksign) {
        this.isbooksign = isbooksign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.BookSignDate
     *
     * @return the value of OpenSale_House.BookSignDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Date getBooksigndate() {
        return booksigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.BookSignDate
     *
     * @param booksigndate the value for OpenSale_House.BookSignDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setBooksigndate(Date booksigndate) {
        this.booksigndate = booksigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.PaySolution
     *
     * @return the value of OpenSale_House.PaySolution
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getPaysolution() {
        return paysolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.PaySolution
     *
     * @param paysolution the value for OpenSale_House.PaySolution
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setPaysolution(Integer paysolution) {
        this.paysolution = paysolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.FloorSortNo
     *
     * @return the value of OpenSale_House.FloorSortNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getFloorsortno() {
        return floorsortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.FloorSortNo
     *
     * @param floorsortno the value for OpenSale_House.FloorSortNo
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setFloorsortno(Integer floorsortno) {
        this.floorsortno = floorsortno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.LockedBy
     *
     * @return the value of OpenSale_House.LockedBy
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getLockedby() {
        return lockedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.LockedBy
     *
     * @param lockedby the value for OpenSale_House.LockedBy
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setLockedby(Integer lockedby) {
        this.lockedby = lockedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.LockedDate
     *
     * @return the value of OpenSale_House.LockedDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Date getLockeddate() {
        return lockeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.LockedDate
     *
     * @param lockeddate the value for OpenSale_House.LockedDate
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setLockeddate(Date lockeddate) {
        this.lockeddate = lockeddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.SubscribingGuid
     *
     * @return the value of OpenSale_House.SubscribingGuid
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getSubscribingguid() {
        return subscribingguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.SubscribingGuid
     *
     * @param subscribingguid the value for OpenSale_House.SubscribingGuid
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setSubscribingguid(String subscribingguid) {
        this.subscribingguid = subscribingguid == null ? null : subscribingguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.BookPrintTimes
     *
     * @return the value of OpenSale_House.BookPrintTimes
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getBookprinttimes() {
        return bookprinttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.BookPrintTimes
     *
     * @param bookprinttimes the value for OpenSale_House.BookPrintTimes
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setBookprinttimes(Integer bookprinttimes) {
        this.bookprinttimes = bookprinttimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.ProductType
     *
     * @return the value of OpenSale_House.ProductType
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getProducttype() {
        return producttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.ProductType
     *
     * @param producttype the value for OpenSale_House.ProductType
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setProducttype(String producttype) {
        this.producttype = producttype == null ? null : producttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.ProtocolAmount
     *
     * @return the value of OpenSale_House.ProtocolAmount
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getProtocolamount() {
        return protocolamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.ProtocolAmount
     *
     * @param protocolamount the value for OpenSale_House.ProtocolAmount
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setProtocolamount(BigDecimal protocolamount) {
        this.protocolamount = protocolamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.PaymentMethodName
     *
     * @return the value of OpenSale_House.PaymentMethodName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getPaymentmethodname() {
        return paymentmethodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.PaymentMethodName
     *
     * @param paymentmethodname the value for OpenSale_House.PaymentMethodName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setPaymentmethodname(String paymentmethodname) {
        this.paymentmethodname = paymentmethodname == null ? null : paymentmethodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.PayedTime
     *
     * @return the value of OpenSale_House.PayedTime
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Date getPayedtime() {
        return payedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.PayedTime
     *
     * @param payedtime the value for OpenSale_House.PayedTime
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setPayedtime(Date payedtime) {
        this.payedtime = payedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.CustomerNames
     *
     * @return the value of OpenSale_House.CustomerNames
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getCustomernames() {
        return customernames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.CustomerNames
     *
     * @param customernames the value for OpenSale_House.CustomerNames
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setCustomernames(String customernames) {
        this.customernames = customernames == null ? null : customernames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.Nullify
     *
     * @return the value of OpenSale_House.Nullify
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Boolean getNullify() {
        return nullify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.Nullify
     *
     * @param nullify the value for OpenSale_House.Nullify
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setNullify(Boolean nullify) {
        this.nullify = nullify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.SaleID
     *
     * @return the value of OpenSale_House.SaleID
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getSaleid() {
        return saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.SaleID
     *
     * @param saleid the value for OpenSale_House.SaleID
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setSaleid(Integer saleid) {
        this.saleid = saleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.SaleName
     *
     * @return the value of OpenSale_House.SaleName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public String getSalename() {
        return salename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.SaleName
     *
     * @param salename the value for OpenSale_House.SaleName
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setSalename(String salename) {
        this.salename = salename == null ? null : salename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.FloorBuiltPrice
     *
     * @return the value of OpenSale_House.FloorBuiltPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getFloorbuiltprice() {
        return floorbuiltprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.FloorBuiltPrice
     *
     * @param floorbuiltprice the value for OpenSale_House.FloorBuiltPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setFloorbuiltprice(BigDecimal floorbuiltprice) {
        this.floorbuiltprice = floorbuiltprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.FloorSetInPrice
     *
     * @return the value of OpenSale_House.FloorSetInPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getFloorsetinprice() {
        return floorsetinprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.FloorSetInPrice
     *
     * @param floorsetinprice the value for OpenSale_House.FloorSetInPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setFloorsetinprice(BigDecimal floorsetinprice) {
        this.floorsetinprice = floorsetinprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.FloorTotalPrice
     *
     * @return the value of OpenSale_House.FloorTotalPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getFloortotalprice() {
        return floortotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.FloorTotalPrice
     *
     * @param floortotalprice the value for OpenSale_House.FloorTotalPrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setFloortotalprice(BigDecimal floortotalprice) {
        this.floortotalprice = floortotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.DecoratePrice
     *
     * @return the value of OpenSale_House.DecoratePrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public BigDecimal getDecorateprice() {
        return decorateprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.DecoratePrice
     *
     * @param decorateprice the value for OpenSale_House.DecoratePrice
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setDecorateprice(BigDecimal decorateprice) {
        this.decorateprice = decorateprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OpenSale_House.ProductTypeId
     *
     * @return the value of OpenSale_House.ProductTypeId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public Integer getProducttypeid() {
        return producttypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OpenSale_House.ProductTypeId
     *
     * @param producttypeid the value for OpenSale_House.ProductTypeId
     *
     * @mbggenerated Fri Jul 06 09:26:08 CST 2018
     */
    public void setProducttypeid(Integer producttypeid) {
        this.producttypeid = producttypeid;
    }
}