package com.boot.star.model;

import java.io.Serializable;
import java.util.Date;

public class SysRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ID
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_CODE
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_NAME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_SORT
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String roleSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_ADMINFLAG
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String roleAdminflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATE_TIME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CREATE_USER
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.UPDATE_TIME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.UPDATE_USER
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.STATUS
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.RMK
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private String rmk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_TYPE
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    private Integer roleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ID
     *
     * @return the value of sys_role.ID
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ID
     *
     * @param id the value for sys_role.ID
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_CODE
     *
     * @return the value of sys_role.ROLE_CODE
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_CODE
     *
     * @param roleCode the value for sys_role.ROLE_CODE
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_NAME
     *
     * @return the value of sys_role.ROLE_NAME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_NAME
     *
     * @param roleName the value for sys_role.ROLE_NAME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_SORT
     *
     * @return the value of sys_role.ROLE_SORT
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getRoleSort() {
        return roleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_SORT
     *
     * @param roleSort the value for sys_role.ROLE_SORT
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setRoleSort(String roleSort) {
        this.roleSort = roleSort == null ? null : roleSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_ADMINFLAG
     *
     * @return the value of sys_role.ROLE_ADMINFLAG
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getRoleAdminflag() {
        return roleAdminflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_ADMINFLAG
     *
     * @param roleAdminflag the value for sys_role.ROLE_ADMINFLAG
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setRoleAdminflag(String roleAdminflag) {
        this.roleAdminflag = roleAdminflag == null ? null : roleAdminflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATE_TIME
     *
     * @return the value of sys_role.CREATE_TIME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATE_TIME
     *
     * @param createTime the value for sys_role.CREATE_TIME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CREATE_USER
     *
     * @return the value of sys_role.CREATE_USER
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CREATE_USER
     *
     * @param createUser the value for sys_role.CREATE_USER
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.UPDATE_TIME
     *
     * @return the value of sys_role.UPDATE_TIME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.UPDATE_TIME
     *
     * @param updateTime the value for sys_role.UPDATE_TIME
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.UPDATE_USER
     *
     * @return the value of sys_role.UPDATE_USER
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.UPDATE_USER
     *
     * @param updateUser the value for sys_role.UPDATE_USER
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.STATUS
     *
     * @return the value of sys_role.STATUS
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.STATUS
     *
     * @param status the value for sys_role.STATUS
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.RMK
     *
     * @return the value of sys_role.RMK
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.RMK
     *
     * @param rmk the value for sys_role.RMK
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setRmk(String rmk) {
        this.rmk = rmk == null ? null : rmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_TYPE
     *
     * @return the value of sys_role.ROLE_TYPE
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_TYPE
     *
     * @param roleType the value for sys_role.ROLE_TYPE
     *
     * @mbggenerated Fri Sep 21 16:00:38 CST 2018
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }
}