package com.boot.star.model;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Id
     *
     * @mbggenerated Wed Sep 26 14:41:47 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.Name
     *
     * @mbggenerated Wed Sep 26 14:41:47 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Id
     *
     * @return the value of t_user.Id
     *
     * @mbggenerated Wed Sep 26 14:41:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Id
     *
     * @param id the value for t_user.Id
     *
     * @mbggenerated Wed Sep 26 14:41:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.Name
     *
     * @return the value of t_user.Name
     *
     * @mbggenerated Wed Sep 26 14:41:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.Name
     *
     * @param name the value for t_user.Name
     *
     * @mbggenerated Wed Sep 26 14:41:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}